import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Header from "next/header";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce-website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header/> */}
        <Header/>
        <div className="bg-gray-951 py-12">

        {children}
        </div>
        {/* <footer/> */}
        <Footer/>
        </body>
    </html>
  );
}
